# Generated by Django 5.1.4 on 2025-01-08 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TastingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_name', models.CharField(max_length=100, verbose_name='와인 이름')),
                ('wine_type', models.CharField(choices=[('red', '레드'), ('white', '화이트'), ('sparkling', '샴페인'), ('rose', '로제'), ('fortified', '주정강화'), ('other', '기타')], default='red', max_length=20, verbose_name='와인 종류')),
                ('wine_varietal', models.CharField(blank=True, max_length=200, null=True, verbose_name='와인 품종')),
                ('country', models.CharField(choices=[('France', '프랑스'), ('Italy', '이탈리아'), ('USA', '미국'), ('Spain', '스페인'), ('Argentina', '아르헨티나'), ('Australia', '호주'), ('Chile', '칠레'), ('South Africa', 'South Africa'), ('Germany', 'Germany'), ('Portugal', 'Portugal'), ('New Zealand', 'New Zealand'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Greece', 'Greece'), ('Canada', 'Canada'), ('Japan', 'Japan'), ('South Korea', 'South Korea'), ('Brazil', 'Brazil'), ('China', 'China'), ('Switzerland', 'Switzerland'), ('Other', 'Other')], default='Other', max_length=100, verbose_name='국가')),
                ('winery', models.CharField(blank=True, max_length=100, null=True, verbose_name='와이너리')),
                ('vintage', models.IntegerField(blank=True, choices=[(1800, '1800'), (1801, '1801'), (1802, '1802'), (1803, '1803'), (1804, '1804'), (1805, '1805'), (1806, '1806'), (1807, '1807'), (1808, '1808'), (1809, '1809'), (1810, '1810'), (1811, '1811'), (1812, '1812'), (1813, '1813'), (1814, '1814'), (1815, '1815'), (1816, '1816'), (1817, '1817'), (1818, '1818'), (1819, '1819'), (1820, '1820'), (1821, '1821'), (1822, '1822'), (1823, '1823'), (1824, '1824'), (1825, '1825'), (1826, '1826'), (1827, '1827'), (1828, '1828'), (1829, '1829'), (1830, '1830'), (1831, '1831'), (1832, '1832'), (1833, '1833'), (1834, '1834'), (1835, '1835'), (1836, '1836'), (1837, '1837'), (1838, '1838'), (1839, '1839'), (1840, '1840'), (1841, '1841'), (1842, '1842'), (1843, '1843'), (1844, '1844'), (1845, '1845'), (1846, '1846'), (1847, '1847'), (1848, '1848'), (1849, '1849'), (1850, '1850'), (1851, '1851'), (1852, '1852'), (1853, '1853'), (1854, '1854'), (1855, '1855'), (1856, '1856'), (1857, '1857'), (1858, '1858'), (1859, '1859'), (1860, '1860'), (1861, '1861'), (1862, '1862'), (1863, '1863'), (1864, '1864'), (1865, '1865'), (1866, '1866'), (1867, '1867'), (1868, '1868'), (1869, '1869'), (1870, '1870'), (1871, '1871'), (1872, '1872'), (1873, '1873'), (1874, '1874'), (1875, '1875'), (1876, '1876'), (1877, '1877'), (1878, '1878'), (1879, '1879'), (1880, '1880'), (1881, '1881'), (1882, '1882'), (1883, '1883'), (1884, '1884'), (1885, '1885'), (1886, '1886'), (1887, '1887'), (1888, '1888'), (1889, '1889'), (1890, '1890'), (1891, '1891'), (1892, '1892'), (1893, '1893'), (1894, '1894'), (1895, '1895'), (1896, '1896'), (1897, '1897'), (1898, '1898'), (1899, '1899'), (1900, '1900'), (1901, '1901'), (1902, '1902'), (1903, '1903'), (1904, '1904'), (1905, '1905'), (1906, '1906'), (1907, '1907'), (1908, '1908'), (1909, '1909'), (1910, '1910'), (1911, '1911'), (1912, '1912'), (1913, '1913'), (1914, '1914'), (1915, '1915'), (1916, '1916'), (1917, '1917'), (1918, '1918'), (1919, '1919'), (1920, '1920'), (1921, '1921'), (1922, '1922'), (1923, '1923'), (1924, '1924'), (1925, '1925'), (1926, '1926'), (1927, '1927'), (1928, '1928'), (1929, '1929'), (1930, '1930'), (1931, '1931'), (1932, '1932'), (1933, '1933'), (1934, '1934'), (1935, '1935'), (1936, '1936'), (1937, '1937'), (1938, '1938'), (1939, '1939'), (1940, '1940'), (1941, '1941'), (1942, '1942'), (1943, '1943'), (1944, '1944'), (1945, '1945'), (1946, '1946'), (1947, '1947'), (1948, '1948'), (1949, '1949'), (1950, '1950'), (1951, '1951'), (1952, '1952'), (1953, '1953'), (1954, '1954'), (1955, '1955'), (1956, '1956'), (1957, '1957'), (1958, '1958'), (1959, '1959'), (1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], null=True, verbose_name='빈티지')),
                ('tasting_date', models.DateField(verbose_name='테이스팅 날짜')),
                ('tasting_place', models.CharField(default='Unknown', max_length=200, verbose_name='테이스팅 장소')),
                ('appearance_clarity', models.CharField(choices=[('맑음', '맑음'), ('약간 탁함', '약간 탁함'), ('탁함', '탁함'), ('불투명', '불투명')], default='맑음', max_length=20, verbose_name='투명도')),
                ('appearance_intensity', models.PositiveIntegerField(default=3, verbose_name='색의 강도')),
                ('aroma_intensity', models.PositiveIntegerField(default=3, verbose_name='향의 강도')),
                ('aroma_notes', models.TextField(blank=True, null=True, verbose_name='아로마 노트')),
                ('sweetness', models.PositiveIntegerField(default=3, verbose_name='당도')),
                ('acidity', models.PositiveIntegerField(default=3, verbose_name='산도')),
                ('tannin', models.PositiveIntegerField(default=3, verbose_name='탄닌')),
                ('body', models.PositiveIntegerField(default=3, verbose_name='바디')),
                ('overall', models.TextField(blank=True, null=True, verbose_name='종합 평가')),
                ('is_public', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasting_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
