# Generated by Django 5.1.4 on 2025-01-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_tastingnote_tags_alter_tastingnote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tastingnote',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
