# Generated by Django 5.1.4 on 2025-01-09 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_tag_alter_tastingnote_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TastingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tasting_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notes.tastingnote')),
            ],
            options={
                'unique_together': {('tasting_note', 'date')},
            },
        ),
    ]
