# Generated by Django 4.2.16 on 2024-12-24 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TastingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_name', models.CharField(max_length=255)),
                ('winery', models.CharField(blank=True, max_length=255, null=True)),
                ('vintage', models.PositiveIntegerField(blank=True, null=True)),
                ('tasting_date', models.DateField()),
                ('tasting_place', models.CharField(blank=True, max_length=255, null=True)),
                ('appearance', models.TextField(blank=True, null=True)),
                ('aroma', models.TextField(blank=True, null=True)),
                ('taste', models.TextField(blank=True, null=True)),
                ('overall', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasting_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
