# Generated by Django 4.2.16 on 2025-01-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tastingnote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='tastingnote',
            name='appearance',
            field=models.TextField(blank=True, null=True, verbose_name='외관 평가'),
        ),
        migrations.AlterField(
            model_name='tastingnote',
            name='aroma',
            field=models.TextField(blank=True, null=True, verbose_name='아로마'),
        ),
        migrations.AlterField(
            model_name='tastingnote',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='공개 여부'),
        ),
        migrations.AlterField(
            model_name='tastingnote',
            name='overall',
            field=models.TextField(blank=True, null=True, verbose_name='종합 평가'),
        ),
        migrations.AlterField(
            model_name='tastingnote',
            name='taste',
            field=models.TextField(blank=True, null=True, verbose_name='맛 평가'),
        ),
        migrations.AlterField(
            model_name='tastingnote',
            name='tasting_date',
            field=models.DateField(verbose_name='테이스팅 날짜'),
        ),
        migrations.AlterField(
            model_name='tastingnote',
            name='tasting_place',
            field=models.CharField(default='Unknown', max_length=200, verbose_name='테이스팅 장소'),
        ),
        migrations.AlterField(
            model_name='tastingnote',
            name='vintage',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='빈티지'),
        ),
        migrations.AlterField(
            model_name='tastingnote',
            name='wine_name',
            field=models.CharField(max_length=100, verbose_name='와인 이름'),
        ),
        migrations.AlterField(
            model_name='tastingnote',
            name='winery',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='와이너리'),
        ),
    ]
