# Generated by Django 4.2.16 on 2025-01-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_tastingnote_appearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tastingnote',
            name='country',
            field=models.CharField(choices=[('France', '프랑스'), ('Italy', '이탈리아'), ('USA', '미국'), ('Spain', '스페인'), ('Argentina', '아르헨티나'), ('Australia', '호주'), ('Chile', '칠레'), ('South Africa', 'South Africa'), ('Germany', 'Germany'), ('Portugal', 'Portugal'), ('New Zealand', 'New Zealand'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Greece', 'Greece'), ('Canada', 'Canada'), ('Japan', 'Japan'), ('South Korea', 'South Korea'), ('Brazil', 'Brazil'), ('China', 'China'), ('Switzerland', 'Switzerland'), ('Other', 'Other')], default='Other', max_length=100, verbose_name='국가'),
        ),
    ]
